# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${self:custom.secrets.org}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: banzai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: banzai

provider:
    name: aws
    runtime: nodejs20.x
    region: eu-north-1
    deploymentMethod: direct
    iam:
        role: ${self:custom.secrets.role}

custom:
    secrets: ${file(./personal.yml)}

functions:
    GetRooms:
        handler: functions/GetRooms/index.handler
        events:
            - httpApi:
                  path: /rooms
                  method: get
    GetOrders:
        handler: functions/GetOrders/index.handler
        events:
            - httpApi:
                  path: /orders
                  method: get

    PostOrder:
        handler: functions/PostOrder/index.handler
        events:
            - httpApi:
                  path: /orders
                  method: post
    UpdateOrder:
        handler: functions/UpdateOrder/index.handler
        events:
            - httpApi:
                  path: /orders/{orderID}
                  method: put
    DeleteOrder:
        handler: functions/DeleteOrder/index.handler
        events:
            - httpApi:
                  path: /orders/{orderID}
                  method: delete
resources:
    Resources:
        bonzaiRooms:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: bonzaiRooms
                AttributeDefinitions:
                    - AttributeName: roomType
                      AttributeType: S
                KeySchema:
                    - AttributeName: roomType
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST

        bonzaiOrders:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: bonzaiOrders
                AttributeDefinitions:
                    - AttributeName: orderID
                      AttributeType: S
                KeySchema:
                    - AttributeName: orderID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
